[[plugins]]
repository = "briancollins/vim-jst"

[[plugins]]
repository = "pangloss/vim-javascript"

[[plugins]]
repository = "tpope/vim-haml"

[[plugins]]
repository = "rodjek/vim-puppet"

[[plugins]]
repository = "othree/javascript-libraries-syntax.vim"

[[plugins]]
repository = "claco/jasmine.vim"

[[plugins]]
repository = "digitaltoad/vim-jade.git"

[[plugins]]
repository = "groenewege/vim-less.git"

[[plugins]]
repository = "itspriddle/vim-jquery.git"

[[plugins]]
repository = "jtratner/vim-flavored-markdown.git"

[[plugins]]
repository = "kchmck/vim-coffee-script"

[[plugins]]
repository = "scrooloose/syntastic.git"

[[plugins]]
repository = "garbas/vim-snipmate.git"

[[plugins]]
repository = "nelstrom/vim-markdown-preview"

[[plugins]]
repository = "skwp/vim-html-escape"

[[plugins]]
repository = "honza/vim-snippets"

[[plugins]]
repository = "slim-template/vim-slim.git"
