[[plugins]]
repository = "Shougo/vimproc.vim"

  [plugins.build]
  windows = "tools\\update-dll-mingw"
  others = "make"

[[plugins]]
repository = "chrisbra/color_highlight.git"

[[plugins]]
repository = "skwp/vim-colors-solarized"

[[plugins]]
repository = "itchyny/lightline.vim"

[[plugins]]
repository = "bogado/file-line.git"

[[plugins]]
repository = "jby/tmux.vim.git"

[[plugins]]
repository = "morhetz/gruvbox"

[[plugins]]
repository = "xsunsmile/showmarks.git"
