[[plugins]]
repository = "jistr/vim-nerdtree-tabs.git"

[[plugins]]
repository = "scrooloose/nerdtree.git"

[[plugins]]
repository = "kien/ctrlp.vim"

[[plugins]]
repository = "xolox/vim-misc"

[[plugins]]
repository = "xolox/vim-session"
