[[plugins]]
repository = "ecomba/vim-ruby-refactoring"

[[plugins]]
repository = "tpope/vim-rails.git"

[[plugins]]
repository = "tpope/vim-rake.git"

[[plugins]]
repository = "tpope/vim-rvm.git"

[[plugins]]
repository = "vim-ruby/vim-ruby.git"

[[plugins]]
repository = "Keithbsmiley/rspec.vim"

[[plugins]]
repository = "skwp/vim-iterm-rspec"

[[plugins]]
repository = "skwp/vim-spec-finder"

[[plugins]]
repository = "ck3g/vim-change-hash-syntax"

[[plugins]]
repository = "tpope/vim-bundler"
